import type { Part } from "./types";

// A tiny starter library so the app isn't empty on first load.
// Users can add / edit / delete these freely.
export const SEED_PARTS: Part[] = [
  {
    id: "seed-cpu-1",
    category: "cpu",
    name: "Ryzen 7 7800X3D",
    brand: "AMD",
    price: 379,
    socket: "AM5",
    tdp: 120,
    ramType: "DDR5",
    maxRamSpeed: 5200,
    memoryChannels: 2,
    integratedGraphics: true,
    cores: 8,
    boostClock: 5.0,
  },
  {
    id: "seed-cpu-2",
    category: "cpu",
    name: "Core i7-14700K",
    brand: "Intel",
    price: 399,
    socket: "LGA1700",
    tdp: 253,
    ramType: "DDR5",
    maxRamSpeed: 5600,
    memoryChannels: 2,
    integratedGraphics: true,
    cores: 20,
    boostClock: 5.6,
  },
  {
    id: "seed-mobo-1",
    category: "motherboard",
    name: "B650 Tomahawk WiFi",
    brand: "MSI",
    price: 219,
    socket: "AM5",
    chipset: "B650",
    formFactor: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamSpeed: 6400,
    memoryChannels: 2,
    m2Slots: 3,
    sataPorts: 6,
    pcieX16Slots: 1,
    eps8Pin: 2,
  },
  {
    id: "seed-mobo-2",
    category: "motherboard",
    name: "Z790 Aorus Elite AX",
    brand: "Gigabyte",
    price: 269,
    socket: "LGA1700",
    chipset: "Z790",
    formFactor: "ATX",
    ramType: "DDR5",
    ramSlots: 4,
    maxRamSpeed: 7600,
    memoryChannels: 2,
    m2Slots: 4,
    sataPorts: 4,
    pcieX16Slots: 1,
    eps8Pin: 2,
  },
  {
    id: "seed-ram-1",
    category: "ram",
    name: "Vengeance 32GB (2x16) DDR5-6000",
    brand: "Corsair",
    price: 105,
    ramType: "DDR5",
    speed: 6000,
    sizeGb: 16,
    sticks: 2,
  },
  {
    id: "seed-gpu-1",
    category: "gpu",
    name: "RTX 4070 Super Ventus 3X",
    brand: "MSI",
    price: 599,
    lengthMm: 307,
    tdp: 220,
    pcieConnectors: { pin8: 0, pin6: 0, pin12vhpwr: 1 },
  },
  {
    id: "seed-gpu-2",
    category: "gpu",
    name: "RX 7800 XT Pulse",
    brand: "Sapphire",
    price: 499,
    lengthMm: 313,
    tdp: 263,
    pcieConnectors: { pin8: 2, pin6: 0, pin12vhpwr: 0 },
  },
  {
    id: "seed-storage-1",
    category: "storage",
    name: "980 Pro 2TB",
    brand: "Samsung",
    price: 149,
    interface: "M.2 NVMe",
    sizeGb: 2000,
  },
  {
    id: "seed-psu-1",
    category: "psu",
    name: "RM850x 2024",
    brand: "Corsair",
    price: 149,
    wattage: 850,
    formFactor: "ATX",
    efficiency: "80+ Gold",
    pcie8Pin: 4,
    eps8Pin: 2,
    pcie12vhpwr: 1,
    modular: "Full",
  },
  {
    id: "seed-case-1",
    category: "case",
    name: "4000D Airflow",
    brand: "Corsair",
    price: 104,
    supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
    maxGpuLengthMm: 360,
    maxCoolerHeightMm: 170,
    psuFormFactors: ["ATX"],
    radiatorSupport: "360mm front, 280mm top",
  },
  {
    id: "seed-cooler-1",
    category: "cooler",
    name: "Peerless Assassin 120 SE",
    brand: "Thermalright",
    price: 39,
    supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1200", "LGA1151"],
    heightMm: 157,
    tdpRating: 245,
    type: "Air",
  },
  {
    id: "seed-cooler-2",
    category: "cooler",
    name: "NH-L9i-17xx",
    brand: "Noctua",
    price: 55,
    supportedSockets: ["LGA1700"],
    heightMm: 37,
    tdpRating: 95,
    type: "Air",
  },
];
