/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareDataRouteImport } from './routes/share.$data'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDataRoute = ShareDataRouteImport.update({
  id: '/share/$data',
  path: '/share/$data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/share/$data': typeof ShareDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/share/$data': typeof ShareDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/share/$data': typeof ShareDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/builds' | '/library' | '/sitemap.xml' | '/share/$data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builds' | '/library' | '/sitemap.xml' | '/share/$data'
  id:
    | '__root__'
    | '/'
    | '/builds'
    | '/library'
    | '/sitemap.xml'
    | '/share/$data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildsRoute: typeof BuildsRoute
  LibraryRoute: typeof LibraryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ShareDataRoute: typeof ShareDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$data': {
      id: '/share/$data'
      path: '/share/$data'
      fullPath: '/share/$data'
      preLoaderRoute: typeof ShareDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildsRoute: BuildsRoute,
  LibraryRoute: LibraryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ShareDataRoute: ShareDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
